name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: hello-world
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
      - name: Deploy to ECS
        env:
          AWS_REGION: us-east-1a
          CLUSTER_NAME: app-cluster
          SERVICE_NAME: app-service
          IMAGE_URI: ${{ steps.login-ecr.outputs.registry }}/hello-world:${{ github.sha }}
        run: |
          echo "Updating task definition..."
          TASK_DEFINITION=$(jq -n \
            --arg IMAGE_URI "$IMAGE_URI" \
            --arg TASK_NAME "hello-world-task" \
            '{
              containerDefinitions: [{
                name: "hello-world",
                image: $IMAGE_URI,
                essential: true,
                portMappings: [{
                  containerPort: 3000,
                  hostPort: 3000
                }]
              }],
              family: $TASK_NAME,
              networkMode: "awsvpc",
              requiresCompatibilities: ["FARGATE"],
              cpu: "256",
              memory: "512"
            }')

          echo "$TASK_DEFINITION" > task-definition.json
          TASK_REVISION=$(aws ecs register-task-definition \
            --region $AWS_REGION \
            --cli-input-json file://task-definition.json \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)

          echo "Updating service..."
          aws ecs update-service \
            --region $AWS_REGION \
            --cluster $CLUSTER_NAME \
            --service $SERVICE_NAME \
            --task-definition $TASK_REVISION

